# Travis CI is only used to check the lesson and is not involved in its deployment
dist: bionic
language: ruby
rvm:
  - 2.7.1

branches:
  only:
  - gh-pages
  - /.*/

cache:
  apt: true
  bundler: true
  directories:
    - /home/travis/.rvm/
    - $HOME/.cache/pip

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true  # speeds up installation of html-proofer

before_install:
  - sudo apt-get install -y python3-pip
  - python3 -m pip install --upgrade pip setuptools wheel
  - python3 -m pip install pyyaml

before_script:
  - echo '[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"' >> ~/.bashrc

script:
  - make lesson-check
  - make lesson-check-all
  - make site
