# Travis CI is only used to check the lesson and is not involved in its deployment
dist: bionic
language: ruby
rvm:
  - 2.7.1

branches:
  only:
  - gh-pages
  - /.*/

cache:
  apt: true
  bundler: true
  directories:
    - /home/travis/.rvm/
    - $HOME/.cache/pip

before_install:
  - gem install json kramdown jekyll bundler
  - python3 -m pip install --upgrade pip setuptools wheel
  - python3 -m pip install pyyaml

script:
  - make lesson-check
  - make lesson-check-all
  - make site
